### PR TITLE
Kpt package for free5gc operator

### PR DESCRIPTION
**Pull request by SimonTheLeg**
fixes: https://github.com/nephio-project/nephio/issues/237

`kpt live apply` results in the following output, which looks good to me

```log
+ free5gc-operator-controller-controller-5f564b9575-9zqh8 › kube-rbac-proxy
+ free5gc-operator-controller-controller-5f564b9575-9zqh8 › controller
controller 2023-06-06T08:14:19Z INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
controller 2023-06-06T08:14:19Z INFO    setup   starting manager
controller 2023-06-06T08:14:19Z INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
controller 2023-06-06T08:14:19Z INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
controller I0606 08:14:19.021197       1 leaderelection.go:248] attempting to acquire leader lease free5gc/5089c67f.nephio.org...
kube-rbac-proxy I0605 15:21:41.317844       1 main.go:190] Valid token audiences:
kube-rbac-proxy I0605 15:21:41.317923       1 main.go:262] Generating self signed cert as no cert is provided
kube-rbac-proxy I0605 15:21:42.248182       1 main.go:311] Starting TCP socket on 0.0.0.0:8443
kube-rbac-proxy I0605 15:21:42.299794       1 main.go:318] Listening securely on 0.0.0.0:8443
controller I0606 08:14:35.806293       1 leaderelection.go:258] successfully acquired lease free5gc/5089c67f.nephio.org
controller 2023-06-06T08:14:35Z DEBUG   events  free5gc-operator-controller-controller-5f564b9575-9zqh8_7ef3c0e9-dbd2-4324-832d-4eb9609dd0af became leader      {"type": "Normal", "object": {"kind":"Lease","namespace":"free5gc","name":"5089c67f.nephio.org","uid":"0c1c0eb7-cb7b-44c9-8a73-fac80301057e","apiVersion":"coordination.k8s.io/v1","resourceVersion":"78088"}, "reason": "LeaderElection"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "source": "kind source: *v1alpha1.UPFDeployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "source": "kind source: *v1.Deployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "source": "kind source: *v1.ConfigMap"}
controller 2023-06-06T08:14:35Z INFO    Starting Controller     {"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "source": "kind source: *v1alpha1.AMFDeployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "source": "kind source: *v1alpha1.SMFDeployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "source": "kind source: *v1.Deployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "source": "kind source: *v1.Deployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "source": "kind source: *v1.ConfigMap"}
controller 2023-06-06T08:14:35Z INFO    Starting Controller     {"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment"}
controller 2023-06-06T08:14:35Z INFO    Starting EventSource    {"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "source": "kind source: *v1.ConfigMap"}
controller 2023-06-06T08:14:35Z INFO    Starting Controller     {"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment"}
controller 2023-06-06T08:14:35Z INFO    Starting workers        {"controller": "upfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "UPFDeployment", "worker count": 1}
controller 2023-06-06T08:14:35Z INFO    Starting workers        {"controller": "amfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "AMFDeployment", "worker count": 1}
controller 2023-06-06T08:14:35Z INFO    Starting workers        {"controller": "smfdeployment", "controllerGroup": "workload.nephio.org", "controllerKind": "SMFDeployment", "worker count": 1}

```

Open questions from my side:
1. Would it make sense to rename the component from "free5gc-operator-controller" to "free5gc-operator"? I think this would also shorten object names which are sometimes `free5gc-operator-controller-controller-controller-role` to be more readable and don't stutter.
2. Since one major principal behind kpt is configuration as data, what should the default for `app.kubernetes.io/version` be? Can we just `main` since using it from source will always be a dev state?
3. What is the correct way to handle namespace? Without adding it as a resource (see b343641), the following error occurs 'error: task failed (action: "Inventory", name: "inventory-add-0"): namespaces "free5gc" not found'

### CODE REVIEW

**Comment by SimonTheLeg** [comment]
okay I have updated permissions for now to match what you have posted/ what is generated by controller-gen. 

One remark from my side after looking at https://github.com/nephio-project/free5gc/blob/cc808e3f1b727d2db48b62e8e74843425db43428/config/rbac/role.yaml. Is there anything preventing us from making this aligned between the repositories? I think this would also make it easier for us to later write a CI pipeline that just copies over the file.

From what I can see only the name and namespace of the objects are different

**Comment by denysaleksandrov** [comment]
> 

that role.yaml is not entirely correct. I will update it via PR.

**Comment by denysaleksandrov** [comment]
>> Would it make sense to rename the component from "free5gc-operator-controller" to "free5gc-operator"? I think this would also shorten object names which are sometimes free5gc-operator-controller-controller-controller-role to be more readable and don't stutter.
Moving to "free5gc-operator" makes sense. "-controller" prefix is redundant.

**Comment by johnbelamaric** [comment]
/approve

I would prefer someone from the workload cluster subproject do the final LGTM though, to make sure nothing is missed - @tliron @denysaleksandrov ?

**Pull request merged**
